# Generated by Django 5.2.8 on 2025-12-11 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('file_id', models.BigAutoField(db_column='FILE_ID', primary_key=True, serialize=False)),
                ('file_path', models.FileField(db_column='FILE_PATH', max_length=500, upload_to='videos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': '파일 정보',
                'verbose_name_plural': '파일 정보 목록',
                'db_table': 'FILE_INFO',
            },
        ),
        migrations.CreateModel(
            name='HighlightVideo',
            fields=[
                ('video_file', models.OneToOneField(db_column='VIDEO_FILE_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='videos.fileinfo')),
                ('highlight_title', models.CharField(db_column='HIGHLIGHT_TITLE', max_length=100)),
                ('match_date', models.DateField(db_column='MATCH_DATE')),
                ('video_category', models.ForeignKey(db_column='VIDEO_CATEGORY', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.commoncode')),
            ],
            options={
                'verbose_name': '하이라이트 영상',
                'verbose_name_plural': '하이라이트 영상 목록',
                'db_table': 'HIGHLIGHT_VIDEO',
            },
        ),
        migrations.CreateModel(
            name='UserUploadVideo',
            fields=[
                ('upload_file', models.OneToOneField(db_column='UPLOAD_FILE_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='videos.fileinfo')),
                ('upload_title', models.CharField(db_column='UPLOAD_TITLE', max_length=100)),
                ('download_count', models.IntegerField(db_column='DOWNLOAD_COUNT', default=0)),
                ('upload_date', models.DateField(db_column='UPLOAD_DATE')),
                ('use_yn', models.BooleanField(db_column='USE_YN', default=True)),
                ('upload_status_code', models.ForeignKey(db_column='UPLOAD_STATUS_CODE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.commoncode')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to='users.userinfo')),
            ],
            options={
                'verbose_name': '유저 업로드 영상',
                'verbose_name_plural': '유저 업로드 영상 목록',
                'db_table': 'USER_UPLOAD_VIDEO',
            },
        ),
        migrations.CreateModel(
            name='SubtitleInfo',
            fields=[
                ('subtitle_id', models.BigAutoField(db_column='SUBTITLE_ID', primary_key=True, serialize=False)),
                ('subtitle', models.BinaryField(db_column='SUBTITLE')),
                ('commentator_code', models.ForeignKey(db_column='COMMENTATOR_CODE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.commoncode')),
                ('video_file', models.ForeignKey(blank=True, db_column='VIDEO_FILE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.highlightvideo')),
                ('upload_file', models.ForeignKey(blank=True, db_column='UPLOAD_FILE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.useruploadvideo')),
            ],
            options={
                'verbose_name': '자막 정보',
                'verbose_name_plural': '자막 정보 목록',
                'db_table': 'SUBTITLE_INFO',
            },
        ),
    ]
