# Generated by Django 5.2.8 on 2025-12-11 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceInfo',
            fields=[
                ('invoice_id', models.BigAutoField(db_column='INVOICE_ID', primary_key=True, serialize=False)),
                ('invoice_amount', models.BigIntegerField(db_column='INVOICE_AMOUNT')),
                ('issue_date', models.DateField(db_column='ISSUE_DATE')),
            ],
            options={
                'verbose_name': '청구 정보',
                'verbose_name_plural': '청구 정보 목록',
                'db_table': 'INVOICE_INFO',
            },
        ),
        migrations.CreateModel(
            name='PlanInfo',
            fields=[
                ('plan_id', models.BigAutoField(db_column='PLAN_ID', primary_key=True, serialize=False)),
                ('plan_name', models.CharField(db_column='PLAN_NAME', max_length=30)),
                ('price', models.BigIntegerField(db_column='PRICE')),
                ('storage_limit', models.IntegerField(db_column='STORAGE_LIMIT', help_text='단위: KB')),
            ],
            options={
                'verbose_name': '플랜 정보',
                'verbose_name_plural': '플랜 정보 목록',
                'db_table': 'PLAN_INFO',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('payment_id', models.BigAutoField(db_column='PAYMENT_ID', primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_column='TRANSACTION_ID', max_length=100)),
                ('payment_amount', models.BigIntegerField(db_column='PAYMENT_AMOUNT')),
                ('fail_reason', models.CharField(blank=True, db_column='FAIL_REASON', max_length=255, null=True)),
                ('payment_date', models.DateTimeField(db_column='PAYMENT_DATE')),
                ('invoice', models.ForeignKey(db_column='INVOICE_ID', on_delete=django.db.models.deletion.CASCADE, to='payments.invoiceinfo')),
            ],
            options={
                'verbose_name': '결제 이력',
                'verbose_name_plural': '결제 이력 목록',
                'db_table': 'PAYMENT_HISTORY',
            },
        ),
        migrations.CreateModel(
            name='SubscribeHistory',
            fields=[
                ('subscription_id', models.BigAutoField(db_column='SUBSCRIPTION_ID', primary_key=True, serialize=False)),
                ('subscribe_start_dt', models.DateTimeField(db_column='SUBSCRIBE_START_DT')),
                ('subscribe_end_dt', models.DateTimeField(blank=True, db_column='SUBSCRIBE_END_DT', null=True)),
                ('plan', models.ForeignKey(db_column='PLAN_ID', on_delete=django.db.models.deletion.CASCADE, to='payments.planinfo')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to='users.userinfo')),
            ],
            options={
                'verbose_name': '구독 이력',
                'verbose_name_plural': '구독 이력 목록',
                'db_table': 'SUBSCRIBE_HISTORY',
            },
        ),
        migrations.AddField(
            model_name='invoiceinfo',
            name='subscription',
            field=models.ForeignKey(db_column='SUBSCRIPTION_ID', on_delete=django.db.models.deletion.CASCADE, to='payments.subscribehistory'),
        ),
    ]
