# Generated by Django 5.2.8 on 2025-12-11 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCode',
            fields=[
                ('common_code', models.BigAutoField(db_column='COMMON_CODE', primary_key=True, serialize=False)),
                ('common_code_grp', models.CharField(db_column='COMMON_CODE_GRP', max_length=100)),
                ('common_code_value', models.CharField(db_column='COMMON_CODE_VALUE', max_length=100)),
            ],
            options={
                'verbose_name': '공통 코드',
                'verbose_name_plural': '공통 코드 목록',
                'db_table': 'COMMON_CODE',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(db_column='USER_ID', help_text='이메일로 UUID 생성', max_length=40, primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='EMAIL', max_length=254)),
                ('password', models.CharField(db_column='PASSWORD', help_text='영소문자와 숫자 포함 10~16자, 암호화', max_length=64)),
                ('storage_usage', models.IntegerField(db_column='STORAGE_USAGE', default=0, help_text='단위: KB')),
                ('free_use_yn', models.BooleanField(db_column='FREE_USE_YN', default=False)),
                ('favorite_code', models.ForeignKey(blank=True, db_column='FAVORITE_CODE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_favorite', to='users.commoncode')),
            ],
            options={
                'verbose_name': '회원 정보',
                'verbose_name_plural': '회원 정보 목록',
                'db_table': 'USER_INFO',
            },
        ),
    ]
