# Generated by Django 5.2.8 on 2025-12-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('chatbot_id', models.AutoField(primary_key=True, serialize=False)),
                ('rule', models.CharField(help_text='유저 질문에 포함된 핵심 키워드', max_length=30)),
                ('response', models.CharField(help_text='챗봇의 답변', max_length=500)),
            ],
            options={
                'verbose_name': '챗봇',
                'db_table': 'CHATBOT',
            },
        ),
    ]
